agents:
  queue: "default"

steps:
  - command: "buildkite-agent pipeline upload"
    label: ":pipeline:"

  - command: "make restore clean"
    label: "Restore and clean"

  - wait

  - command: "make build test"
    label: "Build and test"