agents:
  queue: "default"

steps:
  - command: "make restore clean"
    label: "Restore and clean"

  - wait

  - command: "make build test"
    label: "Build and test"

  - wait

  - command: "make publish"
    label: "Publish and clean"