agents:
  queue: "default"

steps:
  - command: "make restore clean"
    label: "restore and clean project"
    plugins:
      - docker#v3.12.0:
          image: "mcr.microsoft.com/dotnet/core/sdk:3.1-buster"
          always-pull: true

  - wait

  - command: "make build test"
    label: "build and test project"
    plugins:
      - docker#v3.12.0:
          image: "mcr.microsoft.com/dotnet/core/sdk:3.1-buster"
          always-pull: true

  # - wait

  # - command: "make publish clean"
  #   label: "Publish and clean"

  # - wait

  # - command: "make upload cleanup"
  #   label: "Upload to S3 and cleanup"