agents:
  queue: "default"

steps:
  - label: "Build and upload to S3"
    command: make upload

  # - label: "Build and Test"
  #   command: make build test

  # - wait

  # - label: "Publish and Upload"
  #   command: make publish upload

  # - label: ":docker: run restore, clean, build, test and publish"
  #   commands: 
  #     - "dotnet restore"
  #     - "dotnet clean"
  #     - "dotnet build -c Release"
  #     - "dotnet test AwsTest.Tests/AwsTest.Tests.csproj"
  #     - "dotnet publish -o Publish"
  #     - "ls -lha Publish/"
  #     - "zip "
  #   plugins:
  #     - docker#v3.12.0:
  #         image: "mcr.microsoft.com/dotnet/core/sdk:3.1-buster"
  #         always-pull: true
    #   - docker#v3.12.0:
    #       image: "amazon/aws-cli:latest"
    #       always-pull: true
    #       command: ["s3", "sync", "s3://my-bucket/dist/", "/app/dist"]
    # artifact_paths: "dist/**"          

  # - wait

  # - label: ":docker: run dotnet build and test project :bomb:"
  #   commands: 
  #     - "dotnet build -c Release"
  #     - "dotnet test AwsTest.Tests/AwsTest.Tests.csproj"
  #   plugins:
  #     - docker#v3.12.0:
  #         image: "mcr.microsoft.com/dotnet/core/sdk:3.1-buster"
  #         always-pull: true

  # - wait

  # - label: ":docker: run dotnet publish project"
  #   command: "dotnet publish -o Publish"
  #   plugins:
  #     - docker#v3.12.0:
  #         image: "mcr.microsoft.com/dotnet/core/sdk:3.1-buster"
  #         always-pull: true

  # - wait

  # - command: "make upload cleanup"
  #   label: "Upload to S3 and cleanup"