agents:
  queue: "default"

steps:
  - commands: 
      - "dotnet restore"
      - "dotnet clean"
    label: "restore and clean project"
    plugins:
      - docker#v3.12.0:
          image: "mcr.microsoft.com/dotnet/core/sdk:3.1-buster"
          always-pull: true

  - wait

  - commands: 
      - "dotnet build -c Release"
      - "dotnet test AwsTest.Tests/AwsTest.Tests.csproj"
    label: "build and test project"
    plugins:
      - docker#v3.12.0:
          image: "mcr.microsoft.com/dotnet/core/sdk:3.1-buster"
          always-pull: true

  # - wait

  # - command: "make publish clean"
  #   label: "Publish and clean"

  # - wait

  # - command: "make upload cleanup"
  #   label: "Upload to S3 and cleanup"